apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devx-backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/adr-location: docs/adrs
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
